### ISSUE TITLE
Highlighting with vertico

### ISSUE THREAD

**Issue by BlueDrink9** [axelf4/fizz.el#2]
Hotfuzz seems to be working brilliantly with vertico, but there is no indication of which parts of the results are resulting from matching which letters. Is that something that would need to be implemented on the hotfuzz side or vertico side?

**Comment by ghosty141** [comment]
From the Readme:

**Note:** For now highlighting is only applied with `hotfuzz-selectrum-mode`
because doing it for the default completions API would require
the highlighting to be computed even for completions that are not displayed.

This is a dealbreaker for me. Makes it completely unusable for me.

**Comment by axelf4** [comment]
I have pushed a commit that lets you choose to highlight the first N completions (or all completions,) when using together with Vertico, company-capf or similar, which I believe is a good compromise. Beyond that support for lazy highlighting would need to be added to Emacs proper, or made customizable in Vertico. The dynamic module should now also be usable with Vertico which I can recommend.
