### ISSUE TITLE
Error when using Fido and Org

### ISSUE THREAD

**Issue by scalisi** [axelf4/fizz.el#7]
The following error message is displayed in the minibuffer when inserting a link into an [Org file](https://orgmode.org/manual/Summary.html) when [Fido](https://www.gnu.org/software/emacs/manual/html_node/emacs/Icomplete.html) is enabled and hotfuzz is the completion style:

```
[Error in post-command-hook (icomplete-post-command-hook): (wrong-type-argument listp 0)]
```

The error occurs during the completion of a [link's protocol](https://orgmode.org/manual/External-Links.html). The error occurs immediately after the first character is entered. The error message disappears immediately after a subsequent character is entered.

The error does not occur with any other completion style that I tested.

I found two Icomplete settings that prevent the error. Either of the following settings does the trick:

```elisp
(setq icomplete-max-delay-chars 0)
```

```elisp
(advice-add 'icomplete--fido-mode-setup :after
            (lambda () (setq-local icomplete-show-matches-on-no-input nil)))
```

**Comment by axelf4** [comment]
Hmm, seems to be caused by Icomplete calling `completion-all-completions` with an improper list as completion table (where the CDR of the last cell is `0` as seen in the error.) All other completion styles you tried probably unconditionally called into `all-completions` which does not care and returns a proper list with the `0` removed. I would say this is a bug in Icomplete since the [definition](https://www.gnu.org/software/emacs/manual/html_node/elisp/Basic-Completion.html#index-try_002dcompletion) of *completion table* does not mention improper lists being allowed.

Do you think you could ask on the Icomplete bug tracker if this is something they would be willing to fix?

**Comment by scalisi** [comment]
Hi, Axel. I submitted a bug report to bug-gnu-emacs. I'll let you know what their response is.

By the way, thanks for hotfuzz. The sorting is much better than flex, flx, etc. for me.

**Comment by scalisi** [comment]
There was no response on bug-gnu-emacs.

To anyone else who encounters this problem, there's another workaround in addition to the two above: hotfuzz can be used to complete only certain types of text by setting the [completion-category-overrides](https://www.gnu.org/software/emacs/manual/html_node/elisp/Completion-Variables.html#index-completion_002dcategory_002doverrides) variable.

```elisp
(setq completion-category-overrides '((buffer (styles hotfuzz))
                                      (file (styles hotfuzz))))
```

I'm currently using the above setting because I think I might prefer flex or flx for command completion because their sorting of commands is influenced by recency, which doesn't seem to be the case for hotfuzz; whereas, I think hotfuzz does a much better job sorting buffers than flex and flx.
